### ISSUE TITLE
replace quamash

### ISSUE THREAD

**Issue by Rapiz1** [feeluown/FeelUOwn#346] opened 2020-02-15 15:55 UTC
**Describe the bug**
`asyncio.sleep` does not work in `feeluown` causing album covers can't load properly and many trouble to plugins development.

**To Reproduce**
1. Go to album table view

**Expected behavior**
All pics can load.
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20105061/74590933-2f551e00-504e-11ea-8d81-a1903cdb9951.png)

**Desktop:**
 - OS: Arch Linux
 - Version: 3.3.10

**Additional context**
```
[2020-02-15 23:44:20,386 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-22' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,387 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-23' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,388 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-24' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,388 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-25' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,389 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-26' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,389 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-27' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
[2020-02-15 23:44:20,389 ERROR __init__] : Task exception was never retrieved
future: <Task finished name='Task-28' coro=<fetch_album_cover_wrapper.<locals>.fetch_album_cover() done, defined at /usr/lib/python3.8/site-packages/feeluown/containers/table.py:28> exception=RuntimeError('no running event loop')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feeluown/containers/table.py", line 34, in fetch_album_cover
    await asyncio.sleep(random.randrange(100) / 100)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 637, in sleep
    loop = events.get_running_loop()
RuntimeError: no running event loop
```

**Comment by Rapiz1** [comment] 2020-02-15 16:13
Refer to https://github.com/gmarull/asyncqt/issues/3#issuecomment-571209394
replace `quamash` with `qasync` could solve this problem.
should look for reliable package.

**Comment by cosven** [comment] 2020-02-24 14:57
We may add qasync support for those who use Python>=3.6, as for Python==3.5 users, they may still use quamash.

Maybe we should build a compat layer for these library.

**Comment by TheGreatCabbage** [comment] 2020-03-01 20:35
Hi, I can confirm that this problem should be fixed in `qasync`.

> 
> 
> We may add qasync support for those who use Python>=3.6, as for Python==3.5 users, they can still use quamash.
> 
> Maybe we should add a compat layer in feeluown for these libraries.

Since `qasync` is a very close fork of `asyncqt`, you could do something like this:

```python
import sys
version = sys.version_info[:2]

if version >= (3,6):
    import qasync
elif version >= (3,5):
    import asyncqt as qasync

### Write code using qasync ###
```

`asyncqt` seems to have revived itself as of a few days ago, and it has merged the same pull request which fixed this problem in `qasync`. However, `asyncqt` has not published a new version to PyPI yet and I'm not sure if it will stay active.

I plan to keep `qasync` maintained and up-to-date with any improvements in `asyncqt`.

**Closed** 2020-03-02 03:53 UTC
Labels: bug

**Comment by cosven** [comment] 2020-03-02 03:54
> Hi, I can confirm that this problem should be fixed in `qasync`.
> 
> > We may add qasync support for those who use Python>=3.6, as for Python==3.5 users, they can still use quamash.
> > Maybe we should add a compat layer in feeluown for these libraries.
> 
> Since `qasync` is a very close fork of `asyncqt` (which supports Python 3.5), you could do something like this:
> 
> ```python
> import sys
> version = sys.version_info[:2]
> 
> if version >= (3,6):
>     import qasync
> elif version >= (3,5):
>     import asyncqt as qasync
> 
> ### Write code using qasync ###
> ```
> 
> `asyncqt` seems to have revived itself as of a few days ago, and it has merged the same pull request which fixed this problem in `qasync`. However, `asyncqt` has not published a new version to PyPI yet and I'm not sure if it will stay active.
> 
> I plan to keep `qasync` maintained and up-to-date with any improvements in `asyncqt`.

Thanks for your advice.
